# app.yaml

runtime: python311
env: standard
entrypoint: gunicorn -b :$PORT src.wsgi:application

handlers:
- url: /static              
  static_dir: staticfiles/  
- url: /media               
  static_dir: mediafiles/   
- url: /.*
  script: auto

runtime_config:
  python_version: 3