service: default
service_account: ispp-backend@appspot.gserviceaccount.com
env: flex
runtime: python311
entrypoint: gunicorn -b :$PORT src.wsgi
handlers:
  - url: /.*
    script: auto

runtime_config:
  python_version: 3